// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSiteInfo: () => typedError<SiteInfo, string>(__TAURI_INVOKE("get_site_info")),
	getLoginState: () => typedError<LoginState, string>(__TAURI_INVOKE("get_login_state")),
	login: () => typedError<null, string>(__TAURI_INVOKE("login")),
	logout: () => typedError<null, string>(__TAURI_INVOKE("logout")),
};

/* Types */
export type AdvancedFeature = {
	name: string,
	value: number,
};

export type Function = {
	name: string,
	version: string,
};

export type LoginError = "LoginWindowClosed" | "IncompatibleWithCurrentWeBeep" | ({ KeyringError: string }) & { TauriError?: never } | ({ TauriError: string }) & { KeyringError?: never };

export type LoginState = ({ Logged: {
	token: string,
} }) & { Error?: never } | "NotLogged" | "Logging" | ({ Error: {
	error: LoginError,
} }) & { Logged?: never };

export type SiteInfo = {
	sitename: string,
	username: string,
	firstname: string,
	lastname: string,
	fullname: string,
	lang: string,
	userid: number,
	siteurl: string,
	userpictureurl: string,
	functions: Function[],
	downloadfiles: number | null,
	uploadfiles: number | null,
	release: string | null,
	version: string | null,
	mobilecssurl: string | null,
	advancedfeatures: AdvancedFeature[] | null,
	usercanmanageownfiles: boolean | null,
	userquota: number | null,
	usermaxuploadfilesize: number | null,
	userhomepage: number | null,
	userhomepageurl: string | null,
	userprivateaccesskey: string | null,
	siteid: number | null,
	sitecalendartype: string | null,
	usercalendartype: string | null,
	userissiteadmin: boolean | null,
	theme: string | null,
	limitconcurrentlogins: number | null,
	usersessionscount: number | null,
	policyagreed: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

